### ISSUE TITLE
"warning C4172: returning address of local variable or temporary" under MSVC 2017

### ISSUE THREAD

**Issue by belchercw** [apriorit/gmock-global#1]
Great enhancement to GMock!  I was working on the same problem and came across your library, which saved me a bunch of work.  Thank you.  Unfortunately I was getting the above compiler warning, as well as a runtime error about leaking mocks:

```
unknown file: ERROR: this mock object should be deleted but never is. Its address is @00558290.
c:\users\chris\workspace\layermockup\dsp\manualidlmockup\communication\client_library\test\clientinterfacegtest.cpp(122): ERROR: this mock object (used in test ClientTest.Mocking) should be deleted but never is. Its address is @94A19829.
ERROR: 2 leaked mock objects found at program exit. Expectations on a mock object is verified when the object is destructed. Leaking a mock means that its expectations aren't verified, which is usually a test bug. If you really intend to leak a mock, you can suppress this error using testing::Mock::AllowLeak(mock_object), or you may use a fake or stub instead of a mock.
```

I compared the guts of MOCK_GLOBAL_FUNC0_ vs. MOCK_METHOD0_ and discovered that the difference is that MOCK_GLOBAL_FUNC0_ returns a reference:
```
 ::testing::MockSpec<__VA_ARGS__>&
```

While MOCK_METHO0_ returns by value.  Not sure why - maybe the latest GMock has changed?  Or maybe because I'm using VS2017?  Under gcc I also get problems:  

```
gmock-global.h:27:52: error: invalid initialization of non-const reference of type ‘testing::internal::MockSpec<void()>&’ from an rvalue of type ‘testing::internal::MockSpec<void()>’
     return GMOCK_MOCKER_(0, constness, Method).With();
```

Simply removing the & from all 15 specializations seems to fix the problems, but given that a large part of  MOCK_GLOBAL_FUNC0_ is an exact duplicate of MOCK_METHOD0_, I subsequently changed to this:

```c++
#define MOCK_GLOBAL_FUNC0_(tn, constness, ct, Method, ...) \
class gmock_globalmock_##Method { \
public:\
  gmock_globalmock_##Method(const char* tag) : m_tag(tag) {}  \
  const char* const m_tag; \
  MOCK_METHOD0(Method, __VA_ARGS__); \
   }; \
   std::unique_ptr< gmock_globalmock_##Method > gmock_globalmock_##Method##_instance;\
   GMOCK_RESULT_(tn, __VA_ARGS__) ct Method() constness { \
         \
       return gmock_globalmock_##Method##_instance->Method();\
      }\
```

which reduces the amount of code to maintain, as well as gives some protection if GMock ever changes the internal implementation of MOCK_METHOD0.

The only issue is that gmock-global supports up to 15 arguments, while GMock only goes up to MOCK_METHOD10, so I can't do the same treatment for MOCK_GLOBAL_FUNC11 - 15.

**Comment by cuprumator** [comment]
@belchercw you can use MOCK_GLOBAL_FUNC11 - 15 with gtest 1.8.1 and in case you use gtest 1.8.0 include https://github.com/apriorit/gmock-more-args/releases/tag/1.0.1. Also see sample https://github.com/apriorit/gmock-global-sample (compatible with gtest 1.8.1)
