### ISSUE TITLE
Can I tell the global mock what should it return?

### ISSUE THREAD

**Issue by mkpankov** [apriorit/gmock-global#4]
In googlemock docs:
```
  ON_CALL(foo, GetSize())                         // #3
      .WillByDefault(Return(1));
```
How can I do something similar with mock of free function? There's no `ON_GLOBAL_CALL` macro or any macro at all, besides `MOCK_GLOBAL_FUNC*` family and `EXPECT_GLOBAL_CALL`.

**Comment by SergiusTheBest** [comment]
Fixed in 1.0.2.
